# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='greeter.proto',
  package='greeter',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rgreeter.proto\x12\x07greeter\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x12\x43ounterStreamReply\x12\x0f\n\x07\x63ounter\x18\x01 \x01(\x05\"\x1b\n\nNamesReply\x12\r\n\x05names\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2\xb2\x01\n\x07Greeter\x12\x36\n\x08SayHello\x12\x15.greeter.HelloRequest\x1a\x13.greeter.HelloReply\x12>\n\rCounterStream\x12\x0e.greeter.Empty\x1a\x1b.greeter.CounterStreamReply0\x01\x12/\n\x08GetNames\x12\x0e.greeter.Empty\x1a\x13.greeter.NamesReplyb\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='greeter.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='greeter.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=54,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='greeter.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='greeter.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=85,
)


_COUNTERSTREAMREPLY = _descriptor.Descriptor(
  name='CounterStreamReply',
  full_name='greeter.CounterStreamReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='counter', full_name='greeter.CounterStreamReply.counter', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=124,
)


_NAMESREPLY = _descriptor.Descriptor(
  name='NamesReply',
  full_name='greeter.NamesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='greeter.NamesReply.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=153,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='greeter.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['CounterStreamReply'] = _COUNTERSTREAMREPLY
DESCRIPTOR.message_types_by_name['NamesReply'] = _NAMESREPLY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

CounterStreamReply = _reflection.GeneratedProtocolMessageType('CounterStreamReply', (_message.Message,), {
  'DESCRIPTOR' : _COUNTERSTREAMREPLY,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.CounterStreamReply)
  })
_sym_db.RegisterMessage(CounterStreamReply)

NamesReply = _reflection.GeneratedProtocolMessageType('NamesReply', (_message.Message,), {
  'DESCRIPTOR' : _NAMESREPLY,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.NamesReply)
  })
_sym_db.RegisterMessage(NamesReply)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.Empty)
  })
_sym_db.RegisterMessage(Empty)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='greeter.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=165,
  serialized_end=343,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='greeter.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CounterStream',
    full_name='greeter.Greeter.CounterStream',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_COUNTERSTREAMREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetNames',
    full_name='greeter.Greeter.GetNames',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_NAMESREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
