# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\x07greeter\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x12\x43ounterStreamReply\x12\x0f\n\x07\x63ounter\x18\x01 \x01(\x05\"\x1b\n\nNamesReply\x12\r\n\x05names\x18\x01 \x03(\t\"\x07\n\x05\x45mpty2\xb2\x01\n\x07Greeter\x12\x36\n\x08SayHello\x12\x15.greeter.HelloRequest\x1a\x13.greeter.HelloReply\x12>\n\rCounterStream\x12\x0e.greeter.Empty\x1a\x1b.greeter.CounterStreamReply0\x01\x12/\n\x08GetNames\x12\x0e.greeter.Empty\x1a\x13.greeter.NamesReplyb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_COUNTERSTREAMREPLY = DESCRIPTOR.message_types_by_name['CounterStreamReply']
_NAMESREPLY = DESCRIPTOR.message_types_by_name['NamesReply']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

CounterStreamReply = _reflection.GeneratedProtocolMessageType('CounterStreamReply', (_message.Message,), {
  'DESCRIPTOR' : _COUNTERSTREAMREPLY,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.CounterStreamReply)
  })
_sym_db.RegisterMessage(CounterStreamReply)

NamesReply = _reflection.GeneratedProtocolMessageType('NamesReply', (_message.Message,), {
  'DESCRIPTOR' : _NAMESREPLY,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.NamesReply)
  })
_sym_db.RegisterMessage(NamesReply)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.Empty)
  })
_sym_db.RegisterMessage(Empty)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=26
  _HELLOREQUEST._serialized_end=54
  _HELLOREPLY._serialized_start=56
  _HELLOREPLY._serialized_end=85
  _COUNTERSTREAMREPLY._serialized_start=87
  _COUNTERSTREAMREPLY._serialized_end=124
  _NAMESREPLY._serialized_start=126
  _NAMESREPLY._serialized_end=153
  _EMPTY._serialized_start=155
  _EMPTY._serialized_end=162
  _GREETER._serialized_start=165
  _GREETER._serialized_end=343
# @@protoc_insertion_point(module_scope)
