# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Account.proto',
  package='metatrader',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rAccount.proto\x12\nmetatrader\"J\n\nAccounInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06\x62roker\x18\x02 \x01(\t\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x0e\n\x06\x64igits\x18\x04 \x01(\x05\"X\n\rAccountStatus\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x02\x12\x0e\n\x06\x65quity\x18\x02 \x01(\x02\x12\x12\n\nusedMargin\x18\x03 \x01(\x02\x12\x12\n\nfreeMargin\x18\x04 \x01(\x02\"\x06\n\x04Void2\x8d\x01\n\x0e\x41\x63\x63ountService\x12:\n\x0eGetAccountInfo\x12\x10.metatrader.Void\x1a\x16.metatrader.AccounInfo\x12?\n\x10GetAccountStatus\x12\x10.metatrader.Void\x1a\x19.metatrader.AccountStatusb\x06proto3'
)




_ACCOUNINFO = _descriptor.Descriptor(
  name='AccounInfo',
  full_name='metatrader.AccounInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='metatrader.AccounInfo.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='broker', full_name='metatrader.AccounInfo.broker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currency', full_name='metatrader.AccounInfo.currency', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='digits', full_name='metatrader.AccounInfo.digits', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=103,
)


_ACCOUNTSTATUS = _descriptor.Descriptor(
  name='AccountStatus',
  full_name='metatrader.AccountStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='balance', full_name='metatrader.AccountStatus.balance', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='equity', full_name='metatrader.AccountStatus.equity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='usedMargin', full_name='metatrader.AccountStatus.usedMargin', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='freeMargin', full_name='metatrader.AccountStatus.freeMargin', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=193,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='metatrader.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['AccounInfo'] = _ACCOUNINFO
DESCRIPTOR.message_types_by_name['AccountStatus'] = _ACCOUNTSTATUS
DESCRIPTOR.message_types_by_name['Void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccounInfo = _reflection.GeneratedProtocolMessageType('AccounInfo', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNINFO,
  '__module__' : 'Account_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.AccounInfo)
  })
_sym_db.RegisterMessage(AccounInfo)

AccountStatus = _reflection.GeneratedProtocolMessageType('AccountStatus', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTSTATUS,
  '__module__' : 'Account_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.AccountStatus)
  })
_sym_db.RegisterMessage(AccountStatus)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'Account_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.Void)
  })
_sym_db.RegisterMessage(Void)



_ACCOUNTSERVICE = _descriptor.ServiceDescriptor(
  name='AccountService',
  full_name='metatrader.AccountService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=204,
  serialized_end=345,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAccountInfo',
    full_name='metatrader.AccountService.GetAccountInfo',
    index=0,
    containing_service=None,
    input_type=_VOID,
    output_type=_ACCOUNINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAccountStatus',
    full_name='metatrader.AccountService.GetAccountStatus',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_ACCOUNTSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACCOUNTSERVICE)

DESCRIPTOR.services_by_name['AccountService'] = _ACCOUNTSERVICE

# @@protoc_insertion_point(module_scope)
