# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Candles_pb2 as Candles__pb2


class CandleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLastCandles = channel.unary_unary(
                '/metatrader.CandleService/GetLastCandles',
                request_serializer=Candles__pb2.GetLastCandlesReq.SerializeToString,
                response_deserializer=Candles__pb2.CandleList.FromString,
                )
        self.GetCandlesSince = channel.unary_unary(
                '/metatrader.CandleService/GetCandlesSince',
                request_serializer=Candles__pb2.GetCandlesSinceReq.SerializeToString,
                response_deserializer=Candles__pb2.CandleList.FromString,
                )


class CandleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLastCandles(self, request, context):
        """Gets an array of the last n candles.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCandlesSince(self, request, context):
        """Gets an array of the last candles since a given date.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CandleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLastCandles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastCandles,
                    request_deserializer=Candles__pb2.GetLastCandlesReq.FromString,
                    response_serializer=Candles__pb2.CandleList.SerializeToString,
            ),
            'GetCandlesSince': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCandlesSince,
                    request_deserializer=Candles__pb2.GetCandlesSinceReq.FromString,
                    response_serializer=Candles__pb2.CandleList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metatrader.CandleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CandleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLastCandles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metatrader.CandleService/GetLastCandles',
            Candles__pb2.GetLastCandlesReq.SerializeToString,
            Candles__pb2.CandleList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCandlesSince(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metatrader.CandleService/GetCandlesSince',
            Candles__pb2.GetCandlesSinceReq.SerializeToString,
            Candles__pb2.CandleList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
