# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Deals_pb2 as Deals__pb2


class DealsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeals = channel.unary_unary(
                '/metatrader.DealsService/GetDeals',
                request_serializer=Deals__pb2.GetDealsReq.SerializeToString,
                response_deserializer=Deals__pb2.DealsList.FromString,
                )


class DealsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDeals(self, request, context):
        """Gets an array of deals.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DealsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeals,
                    request_deserializer=Deals__pb2.GetDealsReq.FromString,
                    response_serializer=Deals__pb2.DealsList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metatrader.DealsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DealsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDeals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metatrader.DealsService/GetDeals',
            Deals__pb2.GetDealsReq.SerializeToString,
            Deals__pb2.DealsList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
