# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Deals.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Deals.proto',
  package='metatrader',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x44\x65\x61ls.proto\x12\nmetatrader\"\xe6\x01\n\x04\x44\x65\x61l\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\"\n\x04type\x18\x03 \x01(\x0e\x32\x14.metatrader.DealType\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x0e\n\x06volume\x18\x07 \x01(\x02\x12\x0e\n\x06profit\x18\x08 \x01(\x02\x12\x0c\n\x04swap\x18\t \x01(\x02\x12\x0b\n\x03\x66\x65\x65\x18\n \x01(\x02\x12\x0c\n\x04time\x18\x0b \x01(\x03\x12\r\n\x05magic\x18\x0c \x01(\x03\x12\x0f\n\x07\x63omment\x18\r \x01(\t\x12&\n\x06reason\x18\x0e \x01(\x0e\x32\x16.metatrader.DealReason\"/\n\x0bGetDealsReq\x12\x10\n\x08\x66romDate\x18\x01 \x01(\x03\x12\x0e\n\x06toDate\x18\x02 \x01(\x03\",\n\tDealsList\x12\x1f\n\x05\x64\x65\x61ls\x18\x01 \x03(\x0b\x32\x10.metatrader.Deal*\xb6\x02\n\x08\x44\x65\x61lType\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01\x12\x0b\n\x07\x42\x41LANCE\x10\x02\x12\n\n\x06\x43REDIT\x10\x03\x12\n\n\x06\x43HARGE\x10\x04\x12\x0e\n\nCORRECTION\x10\x05\x12\t\n\x05\x42ONUS\x10\x06\x12\x0e\n\nCOMMISSION\x10\x07\x12\x14\n\x10\x43OMMISSION_DAILY\x10\x08\x12\x16\n\x12\x43OMMISSION_MONTHLY\x10\t\x12\x1a\n\x16\x43OMMISSION_AGENT_DAILY\x10\n\x12\x1c\n\x18\x43OMMISSION_AGENT_MONTHLY\x10\x0b\x12\x0c\n\x08INTEREST\x10\x0c\x12\x10\n\x0c\x42UY_CANCELED\x10\r\x12\x11\n\rSELL_CANCELED\x10\x0e\x12\r\n\tDDIVIDEND\x10\x0f\x12\x14\n\x10\x44IVIDEND_FRANKED\x10\x10\x12\x07\n\x03TAX\x10\x11*w\n\nDealReason\x12\n\n\x06\x43LIENT\x10\x00\x12\n\n\x06MOBILE\x10\x01\x12\x07\n\x03WEB\x10\x02\x12\n\n\x06\x45XPERT\x10\x03\x12\x06\n\x02SL\x10\x04\x12\x06\n\x02TP\x10\x05\x12\x06\n\x02SO\x10\x06\x12\x0c\n\x08ROLLOVER\x10\x07\x12\x0b\n\x07VMARGIN\x10\x08\x12\t\n\x05SPLIT\x10\t2J\n\x0c\x44\x65\x61lsService\x12:\n\x08GetDeals\x12\x17.metatrader.GetDealsReq\x1a\x15.metatrader.DealsListb\x06proto3'
)

_DEALTYPE = _descriptor.EnumDescriptor(
  name='DealType',
  full_name='metatrader.DealType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BALANCE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CREDIT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHARGE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CORRECTION', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BONUS', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMISSION', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMISSION_DAILY', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMISSION_MONTHLY', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMISSION_AGENT_DAILY', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMMISSION_AGENT_MONTHLY', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTEREST', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUY_CANCELED', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELL_CANCELED', index=14, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DDIVIDEND', index=15, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DIVIDEND_FRANKED', index=16, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TAX', index=17, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=356,
  serialized_end=666,
)
_sym_db.RegisterEnumDescriptor(_DEALTYPE)

DealType = enum_type_wrapper.EnumTypeWrapper(_DEALTYPE)
_DEALREASON = _descriptor.EnumDescriptor(
  name='DealReason',
  full_name='metatrader.DealReason',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLIENT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOBILE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WEB', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXPERT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SL', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TP', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SO', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROLLOVER', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VMARGIN', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SPLIT', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=668,
  serialized_end=787,
)
_sym_db.RegisterEnumDescriptor(_DEALREASON)

DealReason = enum_type_wrapper.EnumTypeWrapper(_DEALREASON)
BUY = 0
SELL = 1
BALANCE = 2
CREDIT = 3
CHARGE = 4
CORRECTION = 5
BONUS = 6
COMMISSION = 7
COMMISSION_DAILY = 8
COMMISSION_MONTHLY = 9
COMMISSION_AGENT_DAILY = 10
COMMISSION_AGENT_MONTHLY = 11
INTEREST = 12
BUY_CANCELED = 13
SELL_CANCELED = 14
DDIVIDEND = 15
DIVIDEND_FRANKED = 16
TAX = 17
CLIENT = 0
MOBILE = 1
WEB = 2
EXPERT = 3
SL = 4
TP = 5
SO = 6
ROLLOVER = 7
VMARGIN = 8
SPLIT = 9



_DEAL = _descriptor.Descriptor(
  name='Deal',
  full_name='metatrader.Deal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='metatrader.Deal.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='metatrader.Deal.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='metatrader.Deal.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='metatrader.Deal.price', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='metatrader.Deal.volume', index=4,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profit', full_name='metatrader.Deal.profit', index=5,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swap', full_name='metatrader.Deal.swap', index=6,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fee', full_name='metatrader.Deal.fee', index=7,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='metatrader.Deal.time', index=8,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magic', full_name='metatrader.Deal.magic', index=9,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='metatrader.Deal.comment', index=10,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='metatrader.Deal.reason', index=11,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=258,
)


_GETDEALSREQ = _descriptor.Descriptor(
  name='GetDealsReq',
  full_name='metatrader.GetDealsReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromDate', full_name='metatrader.GetDealsReq.fromDate', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='toDate', full_name='metatrader.GetDealsReq.toDate', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=307,
)


_DEALSLIST = _descriptor.Descriptor(
  name='DealsList',
  full_name='metatrader.DealsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deals', full_name='metatrader.DealsList.deals', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=353,
)

_DEAL.fields_by_name['type'].enum_type = _DEALTYPE
_DEAL.fields_by_name['reason'].enum_type = _DEALREASON
_DEALSLIST.fields_by_name['deals'].message_type = _DEAL
DESCRIPTOR.message_types_by_name['Deal'] = _DEAL
DESCRIPTOR.message_types_by_name['GetDealsReq'] = _GETDEALSREQ
DESCRIPTOR.message_types_by_name['DealsList'] = _DEALSLIST
DESCRIPTOR.enum_types_by_name['DealType'] = _DEALTYPE
DESCRIPTOR.enum_types_by_name['DealReason'] = _DEALREASON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Deal = _reflection.GeneratedProtocolMessageType('Deal', (_message.Message,), {
  'DESCRIPTOR' : _DEAL,
  '__module__' : 'Deals_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.Deal)
  })
_sym_db.RegisterMessage(Deal)

GetDealsReq = _reflection.GeneratedProtocolMessageType('GetDealsReq', (_message.Message,), {
  'DESCRIPTOR' : _GETDEALSREQ,
  '__module__' : 'Deals_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.GetDealsReq)
  })
_sym_db.RegisterMessage(GetDealsReq)

DealsList = _reflection.GeneratedProtocolMessageType('DealsList', (_message.Message,), {
  'DESCRIPTOR' : _DEALSLIST,
  '__module__' : 'Deals_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.DealsList)
  })
_sym_db.RegisterMessage(DealsList)



_DEALSSERVICE = _descriptor.ServiceDescriptor(
  name='DealsService',
  full_name='metatrader.DealsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=789,
  serialized_end=863,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDeals',
    full_name='metatrader.DealsService.GetDeals',
    index=0,
    containing_service=None,
    input_type=_GETDEALSREQ,
    output_type=_DEALSLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEALSSERVICE)

DESCRIPTOR.services_by_name['DealsService'] = _DEALSSERVICE

# @@protoc_insertion_point(module_scope)
