# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Orders_pb2 as Orders__pb2


class OrdersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrders = channel.unary_unary(
                '/metatrader.OrdersService/GetOrders',
                request_serializer=Orders__pb2.GetOrdersReq.SerializeToString,
                response_deserializer=Orders__pb2.OrdersList.FromString,
                )


class OrdersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOrders(self, request, context):
        """Gets an array of the current open orders.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrdersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=Orders__pb2.GetOrdersReq.FromString,
                    response_serializer=Orders__pb2.OrdersList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metatrader.OrdersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrdersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metatrader.OrdersService/GetOrders',
            Orders__pb2.GetOrdersReq.SerializeToString,
            Orders__pb2.OrdersList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
