# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Orders.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Orders.proto',
  package='metatrader',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cOrders.proto\x12\nmetatrader\"\xdf\x01\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12#\n\x04type\x18\x03 \x01(\x0e\x32\x15.metatrader.OrderType\x12\r\n\x05price\x18\x04 \x01(\x02\x12\n\n\x02sl\x18\x05 \x01(\x02\x12\n\n\x02tp\x18\x06 \x01(\x02\x12\x15\n\rvolumeInitial\x18\x07 \x01(\x02\x12\x15\n\rvolumeCurrent\x18\x08 \x01(\x02\x12\x0c\n\x04time\x18\t \x01(\x03\x12\x12\n\nexpiration\x18\n \x01(\x03\x12\r\n\x05magic\x18\x0b \x01(\x03\x12\x0f\n\x07\x63omment\x18\x0c \x01(\t\".\n\x0cGetOrdersReq\x12\x13\n\x06symbol\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_symbol\"/\n\nOrdersList\x12!\n\x06orders\x18\x01 \x03(\x0b\x32\x11.metatrader.Order*\x9f\x01\n\tOrderType\x12\x0e\n\nBUY_MARKET\x10\x00\x12\x0f\n\x0bSELL_MARKET\x10\x01\x12\r\n\tBUY_LIMIT\x10\x02\x12\x0e\n\nSELL_LIMIT\x10\x03\x12\x0c\n\x08\x42UY_STOP\x10\x04\x12\r\n\tSELL_STOP\x10\x05\x12\x12\n\x0e\x42UY_STOP_LIMIT\x10\x06\x12\x13\n\x0fSELL_STOP_LIMIT\x10\x07\x12\x0c\n\x08\x43LOSE_BY\x10\x08\x32N\n\rOrdersService\x12=\n\tGetOrders\x12\x18.metatrader.GetOrdersReq\x1a\x16.metatrader.OrdersListb\x06proto3'
)

_ORDERTYPE = _descriptor.EnumDescriptor(
  name='OrderType',
  full_name='metatrader.OrderType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUY_MARKET', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELL_MARKET', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUY_LIMIT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELL_LIMIT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUY_STOP', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELL_STOP', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUY_STOP_LIMIT', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELL_STOP_LIMIT', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLOSE_BY', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=352,
  serialized_end=511,
)
_sym_db.RegisterEnumDescriptor(_ORDERTYPE)

OrderType = enum_type_wrapper.EnumTypeWrapper(_ORDERTYPE)
BUY_MARKET = 0
SELL_MARKET = 1
BUY_LIMIT = 2
SELL_LIMIT = 3
BUY_STOP = 4
SELL_STOP = 5
BUY_STOP_LIMIT = 6
SELL_STOP_LIMIT = 7
CLOSE_BY = 8



_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='metatrader.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='metatrader.Order.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='metatrader.Order.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='metatrader.Order.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='metatrader.Order.price', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sl', full_name='metatrader.Order.sl', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tp', full_name='metatrader.Order.tp', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volumeInitial', full_name='metatrader.Order.volumeInitial', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volumeCurrent', full_name='metatrader.Order.volumeCurrent', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='metatrader.Order.time', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiration', full_name='metatrader.Order.expiration', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magic', full_name='metatrader.Order.magic', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='metatrader.Order.comment', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=252,
)


_GETORDERSREQ = _descriptor.Descriptor(
  name='GetOrdersReq',
  full_name='metatrader.GetOrdersReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='metatrader.GetOrdersReq.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_symbol', full_name='metatrader.GetOrdersReq._symbol',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=254,
  serialized_end=300,
)


_ORDERSLIST = _descriptor.Descriptor(
  name='OrdersList',
  full_name='metatrader.OrdersList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='orders', full_name='metatrader.OrdersList.orders', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=349,
)

_ORDER.fields_by_name['type'].enum_type = _ORDERTYPE
_GETORDERSREQ.oneofs_by_name['_symbol'].fields.append(
  _GETORDERSREQ.fields_by_name['symbol'])
_GETORDERSREQ.fields_by_name['symbol'].containing_oneof = _GETORDERSREQ.oneofs_by_name['_symbol']
_ORDERSLIST.fields_by_name['orders'].message_type = _ORDER
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['GetOrdersReq'] = _GETORDERSREQ
DESCRIPTOR.message_types_by_name['OrdersList'] = _ORDERSLIST
DESCRIPTOR.enum_types_by_name['OrderType'] = _ORDERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'Orders_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.Order)
  })
_sym_db.RegisterMessage(Order)

GetOrdersReq = _reflection.GeneratedProtocolMessageType('GetOrdersReq', (_message.Message,), {
  'DESCRIPTOR' : _GETORDERSREQ,
  '__module__' : 'Orders_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.GetOrdersReq)
  })
_sym_db.RegisterMessage(GetOrdersReq)

OrdersList = _reflection.GeneratedProtocolMessageType('OrdersList', (_message.Message,), {
  'DESCRIPTOR' : _ORDERSLIST,
  '__module__' : 'Orders_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.OrdersList)
  })
_sym_db.RegisterMessage(OrdersList)



_ORDERSSERVICE = _descriptor.ServiceDescriptor(
  name='OrdersService',
  full_name='metatrader.OrdersService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=513,
  serialized_end=591,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOrders',
    full_name='metatrader.OrdersService.GetOrders',
    index=0,
    containing_service=None,
    input_type=_GETORDERSREQ,
    output_type=_ORDERSLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERSSERVICE)

DESCRIPTOR.services_by_name['OrdersService'] = _ORDERSSERVICE

# @@protoc_insertion_point(module_scope)
