# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Positions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Positions.proto',
  package='metatrader',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fPositions.proto\x12\nmetatrader\"\xb3\x01\n\x08Position\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12&\n\x04type\x18\x03 \x01(\x0e\x32\x18.metatrader.PositionType\x12\r\n\x05price\x18\x04 \x01(\x02\x12\n\n\x02sl\x18\x05 \x01(\x02\x12\n\n\x02tp\x18\x06 \x01(\x02\x12\x0e\n\x06volume\x18\x07 \x01(\x02\x12\x0c\n\x04time\x18\t \x01(\x03\x12\r\n\x05magic\x18\x0b \x01(\x03\x12\x0f\n\x07\x63omment\x18\x0c \x01(\t\"1\n\x0fGetPositionsReq\x12\x13\n\x06symbol\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_symbol\"8\n\rPositionsList\x12\'\n\tpositions\x18\x01 \x03(\x0b\x32\x14.metatrader.Position\"q\n\x0fOpenPositionReq\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.metatrader.PositionType\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0e\n\x06volume\x18\x03 \x01(\x02\x12\n\n\x02sl\x18\x04 \x01(\x02\x12\n\n\x02tp\x18\x05 \x01(\x02\"!\n\x0fOpenPositionRes\x12\x0e\n\x06ticket\x18\x01 \x01(\x03\";\n\x11ModifyPositionReq\x12\x0e\n\x06ticket\x18\x01 \x01(\x03\x12\n\n\x02sl\x18\x02 \x01(\x02\x12\n\n\x02tp\x18\x03 \x01(\x02\"#\n\x11ModifyPositionRes\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\"\n\x10\x43losePositionReq\x12\x0e\n\x06ticket\x18\x01 \x01(\x03\"\"\n\x10\x43losePositionRes\x12\x0e\n\x06status\x18\x01 \x01(\x08*#\n\x0cPositionType\x12\x08\n\x04LONG\x10\x00\x12\t\n\x05SHORT\x10\x01\x32\xc1\x02\n\x10PositionsService\x12\x46\n\x0cGetPositions\x12\x1b.metatrader.GetPositionsReq\x1a\x19.metatrader.PositionsList\x12H\n\x0cOpenPosition\x12\x1b.metatrader.OpenPositionReq\x1a\x1b.metatrader.OpenPositionRes\x12N\n\x0eModifyPosition\x12\x1d.metatrader.ModifyPositionReq\x1a\x1d.metatrader.ModifyPositionRes\x12K\n\rClosePosition\x12\x1c.metatrader.ClosePositionReq\x1a\x1c.metatrader.ClosePositionResb\x06proto3'
)

_POSITIONTYPE = _descriptor.EnumDescriptor(
  name='PositionType',
  full_name='metatrader.PositionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LONG', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHORT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=642,
  serialized_end=677,
)
_sym_db.RegisterEnumDescriptor(_POSITIONTYPE)

PositionType = enum_type_wrapper.EnumTypeWrapper(_POSITIONTYPE)
LONG = 0
SHORT = 1



_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='metatrader.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='metatrader.Position.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='metatrader.Position.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='metatrader.Position.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='metatrader.Position.price', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sl', full_name='metatrader.Position.sl', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tp', full_name='metatrader.Position.tp', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='metatrader.Position.volume', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='metatrader.Position.time', index=7,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magic', full_name='metatrader.Position.magic', index=8,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comment', full_name='metatrader.Position.comment', index=9,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=211,
)


_GETPOSITIONSREQ = _descriptor.Descriptor(
  name='GetPositionsReq',
  full_name='metatrader.GetPositionsReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='metatrader.GetPositionsReq.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_symbol', full_name='metatrader.GetPositionsReq._symbol',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=213,
  serialized_end=262,
)


_POSITIONSLIST = _descriptor.Descriptor(
  name='PositionsList',
  full_name='metatrader.PositionsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='metatrader.PositionsList.positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=320,
)


_OPENPOSITIONREQ = _descriptor.Descriptor(
  name='OpenPositionReq',
  full_name='metatrader.OpenPositionReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='metatrader.OpenPositionReq.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='metatrader.OpenPositionReq.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='metatrader.OpenPositionReq.volume', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sl', full_name='metatrader.OpenPositionReq.sl', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tp', full_name='metatrader.OpenPositionReq.tp', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=435,
)


_OPENPOSITIONRES = _descriptor.Descriptor(
  name='OpenPositionRes',
  full_name='metatrader.OpenPositionRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket', full_name='metatrader.OpenPositionRes.ticket', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=470,
)


_MODIFYPOSITIONREQ = _descriptor.Descriptor(
  name='ModifyPositionReq',
  full_name='metatrader.ModifyPositionReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket', full_name='metatrader.ModifyPositionReq.ticket', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sl', full_name='metatrader.ModifyPositionReq.sl', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tp', full_name='metatrader.ModifyPositionReq.tp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=531,
)


_MODIFYPOSITIONRES = _descriptor.Descriptor(
  name='ModifyPositionRes',
  full_name='metatrader.ModifyPositionRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='metatrader.ModifyPositionRes.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=568,
)


_CLOSEPOSITIONREQ = _descriptor.Descriptor(
  name='ClosePositionReq',
  full_name='metatrader.ClosePositionReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket', full_name='metatrader.ClosePositionReq.ticket', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=604,
)


_CLOSEPOSITIONRES = _descriptor.Descriptor(
  name='ClosePositionRes',
  full_name='metatrader.ClosePositionRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='metatrader.ClosePositionRes.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=606,
  serialized_end=640,
)

_POSITION.fields_by_name['type'].enum_type = _POSITIONTYPE
_GETPOSITIONSREQ.oneofs_by_name['_symbol'].fields.append(
  _GETPOSITIONSREQ.fields_by_name['symbol'])
_GETPOSITIONSREQ.fields_by_name['symbol'].containing_oneof = _GETPOSITIONSREQ.oneofs_by_name['_symbol']
_POSITIONSLIST.fields_by_name['positions'].message_type = _POSITION
_OPENPOSITIONREQ.fields_by_name['type'].enum_type = _POSITIONTYPE
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['GetPositionsReq'] = _GETPOSITIONSREQ
DESCRIPTOR.message_types_by_name['PositionsList'] = _POSITIONSLIST
DESCRIPTOR.message_types_by_name['OpenPositionReq'] = _OPENPOSITIONREQ
DESCRIPTOR.message_types_by_name['OpenPositionRes'] = _OPENPOSITIONRES
DESCRIPTOR.message_types_by_name['ModifyPositionReq'] = _MODIFYPOSITIONREQ
DESCRIPTOR.message_types_by_name['ModifyPositionRes'] = _MODIFYPOSITIONRES
DESCRIPTOR.message_types_by_name['ClosePositionReq'] = _CLOSEPOSITIONREQ
DESCRIPTOR.message_types_by_name['ClosePositionRes'] = _CLOSEPOSITIONRES
DESCRIPTOR.enum_types_by_name['PositionType'] = _POSITIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'Positions_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.Position)
  })
_sym_db.RegisterMessage(Position)

GetPositionsReq = _reflection.GeneratedProtocolMessageType('GetPositionsReq', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSITIONSREQ,
  '__module__' : 'Positions_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.GetPositionsReq)
  })
_sym_db.RegisterMessage(GetPositionsReq)

PositionsList = _reflection.GeneratedProtocolMessageType('PositionsList', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONSLIST,
  '__module__' : 'Positions_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.PositionsList)
  })
_sym_db.RegisterMessage(PositionsList)

OpenPositionReq = _reflection.GeneratedProtocolMessageType('OpenPositionReq', (_message.Message,), {
  'DESCRIPTOR' : _OPENPOSITIONREQ,
  '__module__' : 'Positions_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.OpenPositionReq)
  })
_sym_db.RegisterMessage(OpenPositionReq)

OpenPositionRes = _reflection.GeneratedProtocolMessageType('OpenPositionRes', (_message.Message,), {
  'DESCRIPTOR' : _OPENPOSITIONRES,
  '__module__' : 'Positions_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.OpenPositionRes)
  })
_sym_db.RegisterMessage(OpenPositionRes)

ModifyPositionReq = _reflection.GeneratedProtocolMessageType('ModifyPositionReq', (_message.Message,), {
  'DESCRIPTOR' : _MODIFYPOSITIONREQ,
  '__module__' : 'Positions_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.ModifyPositionReq)
  })
_sym_db.RegisterMessage(ModifyPositionReq)

ModifyPositionRes = _reflection.GeneratedProtocolMessageType('ModifyPositionRes', (_message.Message,), {
  'DESCRIPTOR' : _MODIFYPOSITIONRES,
  '__module__' : 'Positions_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.ModifyPositionRes)
  })
_sym_db.RegisterMessage(ModifyPositionRes)

ClosePositionReq = _reflection.GeneratedProtocolMessageType('ClosePositionReq', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEPOSITIONREQ,
  '__module__' : 'Positions_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.ClosePositionReq)
  })
_sym_db.RegisterMessage(ClosePositionReq)

ClosePositionRes = _reflection.GeneratedProtocolMessageType('ClosePositionRes', (_message.Message,), {
  'DESCRIPTOR' : _CLOSEPOSITIONRES,
  '__module__' : 'Positions_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.ClosePositionRes)
  })
_sym_db.RegisterMessage(ClosePositionRes)



_POSITIONSSERVICE = _descriptor.ServiceDescriptor(
  name='PositionsService',
  full_name='metatrader.PositionsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=680,
  serialized_end=1001,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPositions',
    full_name='metatrader.PositionsService.GetPositions',
    index=0,
    containing_service=None,
    input_type=_GETPOSITIONSREQ,
    output_type=_POSITIONSLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='OpenPosition',
    full_name='metatrader.PositionsService.OpenPosition',
    index=1,
    containing_service=None,
    input_type=_OPENPOSITIONREQ,
    output_type=_OPENPOSITIONRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ModifyPosition',
    full_name='metatrader.PositionsService.ModifyPosition',
    index=2,
    containing_service=None,
    input_type=_MODIFYPOSITIONREQ,
    output_type=_MODIFYPOSITIONRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ClosePosition',
    full_name='metatrader.PositionsService.ClosePosition',
    index=3,
    containing_service=None,
    input_type=_CLOSEPOSITIONREQ,
    output_type=_CLOSEPOSITIONRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSITIONSSERVICE)

DESCRIPTOR.services_by_name['PositionsService'] = _POSITIONSSERVICE

# @@protoc_insertion_point(module_scope)
