# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServerInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ServerInfo.proto',
  package='metatrader',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10ServerInfo.proto\x12\nmetatrader\"\x07\n\x05\x45mpty\"9\n\rServerTimeRes\x12\x12\n\nserverTime\x18\x01 \x01(\x03\x12\x14\n\x0cterminalPing\x18\x02 \x01(\x02\" \n\x0eMarketWatchReq\x12\x0e\n\x06symbol\x18\x01 \x01(\t\" \n\x0eMarketWatchRes\x12\x0e\n\x06status\x18\x01 \x01(\x08\"%\n\x12MarketWatchListRes\x12\x0f\n\x07symbols\x18\x01 \x03(\t2\xad\x02\n\nServerInfo\x12=\n\rGetServerTime\x12\x11.metatrader.Empty\x1a\x19.metatrader.ServerTimeRes\x12J\n\x10\x41\x64\x64ToMarketWatch\x12\x1a.metatrader.MarketWatchReq\x1a\x1a.metatrader.MarketWatchRes\x12O\n\x15RemoveFromMarketWatch\x12\x1a.metatrader.MarketWatchReq\x1a\x1a.metatrader.MarketWatchRes\x12\x43\n\x0eGetMarketWatch\x12\x11.metatrader.Empty\x1a\x1e.metatrader.MarketWatchListResb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='metatrader.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=39,
)


_SERVERTIMERES = _descriptor.Descriptor(
  name='ServerTimeRes',
  full_name='metatrader.ServerTimeRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverTime', full_name='metatrader.ServerTimeRes.serverTime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='terminalPing', full_name='metatrader.ServerTimeRes.terminalPing', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=98,
)


_MARKETWATCHREQ = _descriptor.Descriptor(
  name='MarketWatchReq',
  full_name='metatrader.MarketWatchReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='metatrader.MarketWatchReq.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=132,
)


_MARKETWATCHRES = _descriptor.Descriptor(
  name='MarketWatchRes',
  full_name='metatrader.MarketWatchRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='metatrader.MarketWatchRes.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=166,
)


_MARKETWATCHLISTRES = _descriptor.Descriptor(
  name='MarketWatchListRes',
  full_name='metatrader.MarketWatchListRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbols', full_name='metatrader.MarketWatchListRes.symbols', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=205,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ServerTimeRes'] = _SERVERTIMERES
DESCRIPTOR.message_types_by_name['MarketWatchReq'] = _MARKETWATCHREQ
DESCRIPTOR.message_types_by_name['MarketWatchRes'] = _MARKETWATCHRES
DESCRIPTOR.message_types_by_name['MarketWatchListRes'] = _MARKETWATCHLISTRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'ServerInfo_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.Empty)
  })
_sym_db.RegisterMessage(Empty)

ServerTimeRes = _reflection.GeneratedProtocolMessageType('ServerTimeRes', (_message.Message,), {
  'DESCRIPTOR' : _SERVERTIMERES,
  '__module__' : 'ServerInfo_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.ServerTimeRes)
  })
_sym_db.RegisterMessage(ServerTimeRes)

MarketWatchReq = _reflection.GeneratedProtocolMessageType('MarketWatchReq', (_message.Message,), {
  'DESCRIPTOR' : _MARKETWATCHREQ,
  '__module__' : 'ServerInfo_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.MarketWatchReq)
  })
_sym_db.RegisterMessage(MarketWatchReq)

MarketWatchRes = _reflection.GeneratedProtocolMessageType('MarketWatchRes', (_message.Message,), {
  'DESCRIPTOR' : _MARKETWATCHRES,
  '__module__' : 'ServerInfo_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.MarketWatchRes)
  })
_sym_db.RegisterMessage(MarketWatchRes)

MarketWatchListRes = _reflection.GeneratedProtocolMessageType('MarketWatchListRes', (_message.Message,), {
  'DESCRIPTOR' : _MARKETWATCHLISTRES,
  '__module__' : 'ServerInfo_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.MarketWatchListRes)
  })
_sym_db.RegisterMessage(MarketWatchListRes)



_SERVERINFO = _descriptor.ServiceDescriptor(
  name='ServerInfo',
  full_name='metatrader.ServerInfo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=208,
  serialized_end=509,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetServerTime',
    full_name='metatrader.ServerInfo.GetServerTime',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SERVERTIMERES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddToMarketWatch',
    full_name='metatrader.ServerInfo.AddToMarketWatch',
    index=1,
    containing_service=None,
    input_type=_MARKETWATCHREQ,
    output_type=_MARKETWATCHRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveFromMarketWatch',
    full_name='metatrader.ServerInfo.RemoveFromMarketWatch',
    index=2,
    containing_service=None,
    input_type=_MARKETWATCHREQ,
    output_type=_MARKETWATCHRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMarketWatch',
    full_name='metatrader.ServerInfo.GetMarketWatch',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MARKETWATCHLISTRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERINFO)

DESCRIPTOR.services_by_name['ServerInfo'] = _SERVERINFO

# @@protoc_insertion_point(module_scope)
