# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Symbols.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Symbols.proto',
  package='metatrader',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rSymbols.proto\x12\nmetatrader\"\x9c\x02\n\nSymbolInfo\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x14\n\x0c\x62\x61seCurrency\x18\x02 \x01(\t\x12\x16\n\x0equotedCurrency\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontractSize\x18\x04 \x01(\x02\x12\x0e\n\x06\x64igits\x18\x05 \x01(\x05\x12\x10\n\x08tickSize\x18\x06 \x01(\x02\x12\x11\n\tvolumeMin\x18\x07 \x01(\x02\x12\x11\n\tvolumeMax\x18\x08 \x01(\x02\x12\x12\n\nvolumeStep\x18\t \x01(\x02\x12&\n\x08swapMode\x18\n \x01(\x0e\x32\x14.metatrader.SwapMode\x12\x10\n\x08swapLong\x18\x0b \x01(\x02\x12\x11\n\tswapShort\x18\x0c \x01(\x02\x12\x11\n\tswap3days\x18\r \x01(\x02\"T\n\x0cSymbolTicker\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x0b\n\x03\x61sk\x18\x02 \x01(\x01\x12\x0b\n\x03\x62id\x18\x03 \x01(\x01\x12\x0c\n\x04last\x18\x04 \x01(\x01\x12\x0e\n\x06volume\x18\x05 \x01(\x03\"3\n\x11GetSymbolInfosReq\x12\x13\n\x06symbol\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_symbol\">\n\x0fSymbolInfosList\x12+\n\x0bsymbolInfos\x18\x01 \x03(\x0b\x32\x16.metatrader.SymbolInfo\"$\n\x12GetSymbolTickerReq\x12\x0e\n\x06symbol\x18\x01 \x01(\t*\xb1\x01\n\x08SwapMode\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\n\n\x06POINTS\x10\x01\x12\x13\n\x0f\x43URRENCY_SYMBOL\x10\x02\x12\x13\n\x0f\x43URRENCY_MARGIN\x10\x03\x12\x14\n\x10\x43URRENCY_DEPOSIT\x10\x04\x12\x14\n\x10INTEREST_CURRENT\x10\x05\x12\x11\n\rINTEREST_OPEN\x10\x06\x12\x12\n\x0eREOPEN_CURRENT\x10\x07\x12\x0e\n\nREOPEN_BID\x10\x08*g\n\tDayOfWeek\x12\n\n\x06SUNDAY\x10\x00\x12\n\n\x06MONDAY\x10\x01\x12\x0b\n\x07TUESDAY\x10\x02\x12\r\n\tWEDNESDAY\x10\x03\x12\x0c\n\x08THURSDAY\x10\x04\x12\n\n\x06\x46RIDAY\x10\x05\x12\x0c\n\x08SATURDAY\x10\x06\x32\xab\x01\n\x0eSymbolsService\x12L\n\x0eGetSymbolInfos\x12\x1d.metatrader.GetSymbolInfosReq\x1a\x1b.metatrader.SymbolInfosList\x12K\n\x0fGetSymbolTicker\x12\x1e.metatrader.GetSymbolTickerReq\x1a\x18.metatrader.SymbolTickerb\x06proto3'
)

_SWAPMODE = _descriptor.EnumDescriptor(
  name='SwapMode',
  full_name='metatrader.SwapMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISABLED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POINTS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CURRENCY_SYMBOL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CURRENCY_MARGIN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CURRENCY_DEPOSIT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTEREST_CURRENT', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTEREST_OPEN', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REOPEN_CURRENT', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REOPEN_BID', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=558,
  serialized_end=735,
)
_sym_db.RegisterEnumDescriptor(_SWAPMODE)

SwapMode = enum_type_wrapper.EnumTypeWrapper(_SWAPMODE)
_DAYOFWEEK = _descriptor.EnumDescriptor(
  name='DayOfWeek',
  full_name='metatrader.DayOfWeek',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUNDAY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MONDAY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TUESDAY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WEDNESDAY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='THURSDAY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FRIDAY', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SATURDAY', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=737,
  serialized_end=840,
)
_sym_db.RegisterEnumDescriptor(_DAYOFWEEK)

DayOfWeek = enum_type_wrapper.EnumTypeWrapper(_DAYOFWEEK)
DISABLED = 0
POINTS = 1
CURRENCY_SYMBOL = 2
CURRENCY_MARGIN = 3
CURRENCY_DEPOSIT = 4
INTEREST_CURRENT = 5
INTEREST_OPEN = 6
REOPEN_CURRENT = 7
REOPEN_BID = 8
SUNDAY = 0
MONDAY = 1
TUESDAY = 2
WEDNESDAY = 3
THURSDAY = 4
FRIDAY = 5
SATURDAY = 6



_SYMBOLINFO = _descriptor.Descriptor(
  name='SymbolInfo',
  full_name='metatrader.SymbolInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='metatrader.SymbolInfo.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='baseCurrency', full_name='metatrader.SymbolInfo.baseCurrency', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quotedCurrency', full_name='metatrader.SymbolInfo.quotedCurrency', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractSize', full_name='metatrader.SymbolInfo.contractSize', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='digits', full_name='metatrader.SymbolInfo.digits', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tickSize', full_name='metatrader.SymbolInfo.tickSize', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volumeMin', full_name='metatrader.SymbolInfo.volumeMin', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volumeMax', full_name='metatrader.SymbolInfo.volumeMax', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volumeStep', full_name='metatrader.SymbolInfo.volumeStep', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swapMode', full_name='metatrader.SymbolInfo.swapMode', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swapLong', full_name='metatrader.SymbolInfo.swapLong', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swapShort', full_name='metatrader.SymbolInfo.swapShort', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swap3days', full_name='metatrader.SymbolInfo.swap3days', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=314,
)


_SYMBOLTICKER = _descriptor.Descriptor(
  name='SymbolTicker',
  full_name='metatrader.SymbolTicker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='metatrader.SymbolTicker.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ask', full_name='metatrader.SymbolTicker.ask', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bid', full_name='metatrader.SymbolTicker.bid', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last', full_name='metatrader.SymbolTicker.last', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='metatrader.SymbolTicker.volume', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=400,
)


_GETSYMBOLINFOSREQ = _descriptor.Descriptor(
  name='GetSymbolInfosReq',
  full_name='metatrader.GetSymbolInfosReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='metatrader.GetSymbolInfosReq.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_symbol', full_name='metatrader.GetSymbolInfosReq._symbol',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=402,
  serialized_end=453,
)


_SYMBOLINFOSLIST = _descriptor.Descriptor(
  name='SymbolInfosList',
  full_name='metatrader.SymbolInfosList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbolInfos', full_name='metatrader.SymbolInfosList.symbolInfos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=517,
)


_GETSYMBOLTICKERREQ = _descriptor.Descriptor(
  name='GetSymbolTickerReq',
  full_name='metatrader.GetSymbolTickerReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='metatrader.GetSymbolTickerReq.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=555,
)

_SYMBOLINFO.fields_by_name['swapMode'].enum_type = _SWAPMODE
_GETSYMBOLINFOSREQ.oneofs_by_name['_symbol'].fields.append(
  _GETSYMBOLINFOSREQ.fields_by_name['symbol'])
_GETSYMBOLINFOSREQ.fields_by_name['symbol'].containing_oneof = _GETSYMBOLINFOSREQ.oneofs_by_name['_symbol']
_SYMBOLINFOSLIST.fields_by_name['symbolInfos'].message_type = _SYMBOLINFO
DESCRIPTOR.message_types_by_name['SymbolInfo'] = _SYMBOLINFO
DESCRIPTOR.message_types_by_name['SymbolTicker'] = _SYMBOLTICKER
DESCRIPTOR.message_types_by_name['GetSymbolInfosReq'] = _GETSYMBOLINFOSREQ
DESCRIPTOR.message_types_by_name['SymbolInfosList'] = _SYMBOLINFOSLIST
DESCRIPTOR.message_types_by_name['GetSymbolTickerReq'] = _GETSYMBOLTICKERREQ
DESCRIPTOR.enum_types_by_name['SwapMode'] = _SWAPMODE
DESCRIPTOR.enum_types_by_name['DayOfWeek'] = _DAYOFWEEK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SymbolInfo = _reflection.GeneratedProtocolMessageType('SymbolInfo', (_message.Message,), {
  'DESCRIPTOR' : _SYMBOLINFO,
  '__module__' : 'Symbols_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.SymbolInfo)
  })
_sym_db.RegisterMessage(SymbolInfo)

SymbolTicker = _reflection.GeneratedProtocolMessageType('SymbolTicker', (_message.Message,), {
  'DESCRIPTOR' : _SYMBOLTICKER,
  '__module__' : 'Symbols_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.SymbolTicker)
  })
_sym_db.RegisterMessage(SymbolTicker)

GetSymbolInfosReq = _reflection.GeneratedProtocolMessageType('GetSymbolInfosReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSYMBOLINFOSREQ,
  '__module__' : 'Symbols_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.GetSymbolInfosReq)
  })
_sym_db.RegisterMessage(GetSymbolInfosReq)

SymbolInfosList = _reflection.GeneratedProtocolMessageType('SymbolInfosList', (_message.Message,), {
  'DESCRIPTOR' : _SYMBOLINFOSLIST,
  '__module__' : 'Symbols_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.SymbolInfosList)
  })
_sym_db.RegisterMessage(SymbolInfosList)

GetSymbolTickerReq = _reflection.GeneratedProtocolMessageType('GetSymbolTickerReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSYMBOLTICKERREQ,
  '__module__' : 'Symbols_pb2'
  # @@protoc_insertion_point(class_scope:metatrader.GetSymbolTickerReq)
  })
_sym_db.RegisterMessage(GetSymbolTickerReq)



_SYMBOLSSERVICE = _descriptor.ServiceDescriptor(
  name='SymbolsService',
  full_name='metatrader.SymbolsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=843,
  serialized_end=1014,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSymbolInfos',
    full_name='metatrader.SymbolsService.GetSymbolInfos',
    index=0,
    containing_service=None,
    input_type=_GETSYMBOLINFOSREQ,
    output_type=_SYMBOLINFOSLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSymbolTicker',
    full_name='metatrader.SymbolsService.GetSymbolTicker',
    index=1,
    containing_service=None,
    input_type=_GETSYMBOLTICKERREQ,
    output_type=_SYMBOLTICKER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYMBOLSSERVICE)

DESCRIPTOR.services_by_name['SymbolsService'] = _SYMBOLSSERVICE

# @@protoc_insertion_point(module_scope)
