name: grpc_dart
description: An application example to test grpc communication in Dart.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  grpc: ^3.0.2
  protobuf: ^2.0.1


dev_dependencies:
  lints: ^1.0.0
